<?php

declare(strict_types=1);

return [
    '/' => ['App\\Controllers\\HomeController', 'index'],
    '/login' => ['App\\Controllers\\Auth\\LoginController', 'index'],
    '/register' => ['App\\Controllers\\Auth\\RegisterController', 'index'],
    '/logout' => ['App\\Controllers\\Auth\\LogoutController', 'logout'],
    '/forgot-password' => ['App\\Controllers\\Auth\\ForgotPasswordController', 'index'],
    '/reset-password' => ['App\\Controllers\\Auth\\ResetPasswordController', 'index'],
    '/verify-email' => ['App\\Controllers\\Auth\\VerificationController', 'verifyEmail'],
    '/dashboard' => ['App\\Controllers\\DashboardController', 'index'],
    '/health' => ['App\\Controllers\\HealthController', 'index'],
    '/ai-assistant' => ['App\\Controllers\\AssistantController', 'index'],
    '/assistant' => ['App\\Controllers\\AssistantController', 'index'],
    '/profile' => ['App\\Controllers\\User\\ProfileController', 'index'],
    '/profile/save' => ['App\\Controllers\\User\\ProfileController', 'save'],
    '/profile/upload-photo' => ['App\\Controllers\\User\\ProfileController', 'uploadPhoto'],
    '/symptom-checker' => ['App\\Controllers\\SymptomCheckerController', 'index'],
    '/symptom-checker/submit' => ['App\\Controllers\\SymptomCheckerController', 'submit'],
    '/symptom-checker/history' => ['App\\Controllers\\SymptomCheckerController', 'history'],
    '/hospital-finder' => ['App\\Controllers\\HospitalFinderController', 'index'],
    '/hospital-finder/search' => ['App\\Controllers\\HospitalFinderController', 'search'],
    '/hospital-finder/nearby-services' => ['App\\Controllers\\HospitalFinderController', 'nearbyServices'],

    '/lab-reports' => ['App\\Controllers\\LabReportController', 'index'],
    '/lab-report' => ['App\\Controllers\\LabReportController', 'index'],
    '/lab-reports/upload' => ['App\\Controllers\\LabReportController', 'upload'],
    '/lab-reports/view' => ['App\\Controllers\\LabReportController', 'show'],
    '/lab-reports/download' => ['App\\Controllers\\LabReportController', 'download'],
    '/lab-reports/delete' => ['App\\Controllers\\LabReportController', 'delete'],
    '/lab-reports/compare' => ['App\\Controllers\\LabReportController', 'compare'],

    '/admin/dashboard' => ['App\\Controllers\\Admin\\DashboardController', 'index'],
    '/admin/users' => ['App\\Controllers\\Admin\\UserController', 'index'],
    '/admin/hospitals' => ['App\\Controllers\\Admin\\HospitalController', 'index'],
    '/admin/hospitals/create' => ['App\\Controllers\\Admin\\HospitalController', 'create'],
    '/admin/hospitals/edit' => ['App\\Controllers\\Admin\\HospitalController', 'edit'],
    '/admin/hospitals/save' => ['App\\Controllers\\Admin\\HospitalController', 'save'],
    '/admin/hospitals/delete' => ['App\\Controllers\\Admin\\HospitalController', 'delete'],
    '/admin/doctors' => ['App\\Controllers\\Admin\\DoctorController', 'index'],
    '/admin/doctors/create' => ['App\\Controllers\\Admin\\DoctorController', 'create'],
    '/admin/doctors/edit' => ['App\\Controllers\\Admin\\DoctorController', 'edit'],
    '/admin/doctors/save' => ['App\\Controllers\\Admin\\DoctorController', 'save'],
    '/admin/doctors/delete' => ['App\\Controllers\\Admin\\DoctorController', 'delete'],
    '/admin/reports' => ['App\\Controllers\\Admin\\ReportController', 'index'],
    '/admin/reports/export-csv' => ['App\\Controllers\\Admin\\ReportController', 'exportCsv'],
    '/admin/reports/export-pdf' => ['App\\Controllers\\Admin\\ReportController', 'exportPdf'],
    '/404' => ['App\\Controllers\\ErrorController', 'notFound'],
];
